CREATE TABLE IF NOT EXISTS account (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    emailVerified TINYINT NOT NULL DEFAULT 0,
    password VARCHAR(255) NOT NULL,
    admin TINYINT NOT NULL DEFAULT 0,
    token VARCHAR(255) NOT NULL
);